apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "MTIzNA=="
  MYSQL_USER: "YWRtaW4="
  MYSQL_PASSWORD: "MTIzNA=="
  MYSQL_HOST: "bXlzcWwtMC5teXNxbC5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbAo="
  DB_CONNECTION: "bXlzcWwrbXlzcWxjb25uZWN0b3I6Ly9hZG1pbjoxMjM0QG15c3FsLTAubXlzcWwubXlzcWwuc3ZjLmNsdXN0ZXIubG9jYWwvdG9kb2xpc3QK"