apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: todoapp
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "MTIzNA=="
  MYSQL_USER: "YWRtaW4="
  MYSQL_PASSWORD: "MTIzNA=="
  MYSQL_HOST: "bXlzcWwtMC5teXNxbC5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbA=="