apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: mysql
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS todolist;
    GRANT ALL PRIVILEGES ON todolist.* TO 'admin'@'%';
    USE todolist;
    CREATE TABLE counter (
      id INT AUTO_INCREMENT PRIMARY KEY,
      value INT
    );